// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ambev.DeveloperEvaluation.Domain.Models;

[Table("Product", Schema = "DeveloperEvaluation")]
[Index("Code", Name = "UQ_Product_Code", IsUnique = true)]
public partial class Product
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(100)]
    public string? Title { get; set; }

    [Precision(10, 2)]
    public decimal? Price { get; set; }

    public int? QuantityInStock { get; set; }

    [StringLength(100)]
    public string? Description { get; set; }

    [StringLength(100)]
    public string? Category { get; set; }

    [StringLength(256)]
    public string? Image { get; set; }

    [StringLength(10)]
    public string? Code { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<SaleItems> SaleItems { get; set; } = new List<SaleItems>();
}