// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ambev.DeveloperEvaluation.Domain.Models;

[Table("User", Schema = "DeveloperEvaluation")]
public partial class User
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Role { get; set; }

    [Required]
    [StringLength(256)]
    public string Email { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [Required]
    [StringLength(512)]
    public string Password { get; set; }

    [StringLength(20)]
    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}