// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Ambev.DeveloperEvaluation.Domain.Common;
using Microsoft.EntityFrameworkCore;

namespace Ambev.DeveloperEvaluation.Domain.Entities;

/// <summary>
/// Cliente
/// </summary>
[Table("Customer", Schema = "DeveloperEvaluation")]
public partial class Customer : BaseEntity
{
    //[Key]
    //public Guid Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(20)]
    public string phone { get; set; }

    [Required]
    [StringLength(256)]
    public string email { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}