// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Ambev.DeveloperEvaluation.Common.Validation;
using Ambev.DeveloperEvaluation.Domain.Validation;
using Microsoft.EntityFrameworkCore;

namespace Ambev.DeveloperEvaluation.Domain.Entities;

/// <summary>
/// Cliente
/// </summary>
[Table("Customer", Schema = "DeveloperEvaluation")]
public partial class Customer
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(20)]
    public string Phone { get; set; }

    [Required]
    [StringLength(256)]
    public string Email { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Sale> Sale { get; set; } = new List<Sale>();

    public ValidationResultDetail Validate()
    {
        var validator = new CustomerValidator();
        var result = validator.Validate(this);
        return new ValidationResultDetail
        {
            IsValid = result.IsValid,
            Errors = result.Errors.Select(o => (ValidationErrorDetail)o)
        };
    }
}