// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Ambev.DeveloperEvaluation.Common.Validation;
using Ambev.DeveloperEvaluation.Domain.Validation;
using Microsoft.EntityFrameworkCore;

namespace Ambev.DeveloperEvaluation.Domain.Entities;

[Table("Product", Schema = "DeveloperEvaluation")]
[Index("Code", Name = "UQ_Product_Code", IsUnique = true)]
public partial class Product
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(10)]
    public string Code { get; set; }

    [StringLength(100)]
    public string Description { get; set; }
    

    [StringLength(256)]
    public string Image { get; set; }

    [Precision(10, 2)]
    public decimal? Price { get; set; }

    public int? QuantityInStock { get; set; }    
   

    [InverseProperty("CodeProductNavigation")]
    public virtual ICollection<SaleItems> SaleItems { get; set; } = new List<SaleItems>();

    public ValidationResultDetail Validate()
    {
        var validator = new ProductValidator();
        var result = validator.Validate(this);
        return new ValidationResultDetail
        {
            IsValid = result.IsValid,
            Errors = result.Errors.Select(o => (ValidationErrorDetail)o)
        };
    }
}