// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Ambev.DeveloperEvaluation.Domain.Common;
using Microsoft.EntityFrameworkCore;

namespace Ambev.DeveloperEvaluation.Domain.Entities;

[Table("Product", Schema = "DeveloperEvaluation")]
public partial class Product : BaseEntity
{
    //[Key]
    //public Guid Id { get; set; }

    [StringLength(100)]
    public string Description { get; set; }

    [Precision(10, 2)]
    public decimal? Prices { get; set; }

    public int? QuantityInStock { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<SaleItems> SaleItems { get; set; } = new List<SaleItems>();
}