// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ambev.DeveloperEvaluation.Domain.Entities;

[Table("SaleItems", Schema = "DeveloperEvaluation")]
public partial class SaleItems
{
    [Key]
    public Guid Id { get; set; }

    public Guid? SaleId { get; set; }

    public Guid? ProductId { get; set; }

    public int? Quantities { get; set; }

    [Precision(10, 2)]
    public decimal? UnitPrices { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("SaleItems")]
    public virtual Product Product { get; set; }

    [ForeignKey("SaleId")]
    [InverseProperty("SaleItems")]
    public virtual Sale Sale { get; set; }
}