// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Ambev.DeveloperEvaluation.Domain.Common;
using Microsoft.EntityFrameworkCore;

namespace Ambev.DeveloperEvaluation.Domain.Entities;

[Table("Sale", Schema = "DeveloperEvaluation")]
public partial class Sale : BaseEntity
{
    //[Key]
    //public Guid Id { get; set; }

    public Guid Customer_Id { get; set; }

    public List<DateTime> SaleDate { get; set; }

    [Precision(12, 2)]
    public decimal? TotalGrossValue { get; set; }

    [Precision(4, 2)]
    public decimal? Discounts { get; set; }

    [Precision(12, 2)]
    public decimal? TotalNetValue { get; set; }

    [Column(TypeName = "bit(1)")]
    public BitArray Cancelled { get; set; }

    [ForeignKey("Customer_Id")]
    [InverseProperty("Sale")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Sale")]
    public virtual ICollection<SaleItems> SaleItems { get; set; } = new List<SaleItems>();
}