// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Ambev.DeveloperEvaluation.Common.Validation;
using Ambev.DeveloperEvaluation.Domain.Validation;
using FluentValidation;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace Ambev.DeveloperEvaluation.Domain.Entities;

[Table("Sale", Schema = "DeveloperEvaluation")]
public partial class Sale
{
    [Key]
    public Guid Id { get; set; }

    public Guid CustomerId { get; set; }

    public DateTime SaleDate { get; set; } = DateTime.UtcNow;

    [Precision(12, 2)]
    public decimal TotalGrossValue { get; set; } = 0;

    [Precision(4, 2)]
    public decimal Discounts { get; set; } = 0;

    [Precision(12, 2)]
    public decimal TotalNetValue { get; set; } = 0;

    public bool Cancelled { get; set; } = false;

    [ForeignKey("CustomerId")]
    [InverseProperty("Sale")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Sale")]
    public virtual ICollection<SaleItems> SaleItems { get; set; } = new List<SaleItems>();

    public ValidationResultDetail Validate()
    {
        var validator = new SaleValidator();
        var result = validator.Validate(this);
        return new ValidationResultDetail
        {
            IsValid = result.IsValid,
            Errors = result.Errors.Select(o => (ValidationErrorDetail)o)
        };
    }


}